# Generated by Django 4.2 on 2023-04-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excursion',
            old_name='num_of_people',
            new_name='max_num_of_people',
        ),
        migrations.AddField(
            model_name='excursion',
            name='num_of_people_now',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
