# Generated by Django 4.2 on 2023-05-03 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='image',
            field=models.ImageField(upload_to='areas_image'),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
                ('Events', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.events')),
                ('Excursion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.excursion')),
                ('Hotels', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.hotels')),
            ],
            options={
                'verbose_name': 'Products',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
