# Generated by Django 4.2 on 2023-05-03 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_area_image_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Events',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.events'),
        ),
        migrations.AlterField(
            model_name='products',
            name='Excursion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.excursion'),
        ),
        migrations.AlterField(
            model_name='products',
            name='Hotels',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hotels'),
        ),
    ]
