# Generated by Django 4.2 on 2023-05-06 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='area',
        ),
    ]
