# Generated by Django 4.2 on 2023-04-19 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_area_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='guide',
            options={'verbose_name': 'Guide', 'verbose_name_plural': 'Guides'},
        ),
    ]
