# Generated by Django 4.2 on 2023-05-03 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_products_events_alter_products_excursion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='Place',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='excursion',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='excursion',
            old_name='Place',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='guide',
            old_name='Excursion',
            new_name='excursion',
        ),
        migrations.RenameField(
            model_name='hotels',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='hotels',
            old_name='Place',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='Area',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Events',
            new_name='events',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Excursion',
            new_name='excursion',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Hotels',
            new_name='hotels',
        ),
    ]
