# Generated by Django 4.2 on 2023-05-02 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_category_events_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='category',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='place',
            new_name='Place',
        ),
        migrations.RenameField(
            model_name='excursion',
            old_name='category',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='excursion',
            old_name='place',
            new_name='Place',
        ),
        migrations.RenameField(
            model_name='guide',
            old_name='excursion',
            new_name='Excursion',
        ),
        migrations.RenameField(
            model_name='hotels',
            old_name='category',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='hotels',
            old_name='place',
            new_name='Place',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='area',
            new_name='Area',
        ),
    ]
